"""add_deleted_at_to_remaining_tables

Revision ID: 81c89ac53559
Revises: b1c2d3e4f5a6
Create Date: 2026-06-04 21:47:18.121526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c89ac53559'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_favourites_student_id', table_name='favourites')
    op.add_column('menu_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messes', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_messes_active_trust', table_name='messes')
    op.create_index(op.f('ix_messes_is_active'), 'messes', ['is_active'], unique=False)
    op.create_index(op.f('ix_messes_pincode'), 'messes', ['pincode'], unique=False)
    op.create_index(op.f('ix_messes_trust_score'), 'messes', ['trust_score'], unique=False)
    op.add_column('reviews', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_reviews_mess_id', table_name='reviews')
    op.drop_index('ix_reviews_student_id', table_name='reviews')
    op.drop_index('uq_one_active_review_per_student_mess', table_name='reviews', postgresql_where='(is_active = true)')
    op.create_unique_constraint('uq_one_review_per_student_mess', 'reviews', ['student_id', 'mess_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_one_review_per_student_mess', 'reviews', type_='unique')
    op.create_index('uq_one_active_review_per_student_mess', 'reviews', ['student_id', 'mess_id'], unique=True, postgresql_where='(is_active = true)')
    op.create_index('ix_reviews_student_id', 'reviews', ['student_id'], unique=False)
    op.create_index('ix_reviews_mess_id', 'reviews', ['mess_id'], unique=False)
    op.drop_column('reviews', 'deleted_at')
    op.drop_index(op.f('ix_messes_trust_score'), table_name='messes')
    op.drop_index(op.f('ix_messes_pincode'), table_name='messes')
    op.drop_index(op.f('ix_messes_is_active'), table_name='messes')
    op.create_index('ix_messes_active_trust', 'messes', ['is_active', 'trust_score'], unique=False)
    op.alter_column('messes', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('menu_items', 'deleted_at')
    op.create_index('ix_favourites_student_id', 'favourites', ['student_id'], unique=False)
    op.drop_column('favourites', 'deleted_at')
    # ### end Alembic commands ###
