"""Add UX enhancement fields to Mess

Revision ID: e3aa0fb3e812
Revises: 768b89537d5a
Create Date: 2026-05-10 13:45:11.342799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add UX enhancement fields to Mess

Revision ID: e3aa0fb3e812
Revises: 768b89537d5a
Create Date: 2026-05-10 13:45:11.342799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3aa0fb3e812'
down_revision: Union[str, None] = '768b89537d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messes', sa.Column('gallery_images', sa.String(), nullable=True))
    op.add_column('messes', sa.Column('owner_phone', sa.String(length=15), nullable=True))
    op.add_column('messes', sa.Column('breakfast_time', sa.String(length=50), nullable=True))
    op.add_column('messes', sa.Column('lunch_time', sa.String(length=50), nullable=True))
    op.add_column('messes', sa.Column('dinner_time', sa.String(length=50), nullable=True))
    op.add_column('messes', sa.Column('monthly_price', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('messes', sa.Column('weekly_price', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messes', 'weekly_price')
    op.drop_column('messes', 'monthly_price')
    op.drop_column('messes', 'dinner_time')
    op.drop_column('messes', 'lunch_time')
    op.drop_column('messes', 'breakfast_time')
    op.drop_column('messes', 'owner_phone')
    op.drop_column('messes', 'gallery_images')
    # ### end Alembic commands ###
